SHOW DATABASES;
DROP DATABASE `wanderer`;
CREATE DATABASE IF NOT EXISTS `wanderer` DEFAULT CHARACTER SET utf8;
SHOW TABLES FROM `wanderer`;

SHOW CREATE TABLE `posts`;
SHOW COLUMNS FROM `posts`;
SELECT * FROM `posts` ORDER BY `id` DESC LIMIT 5;
