:header = <<
Content-Type: application/json
Accept: application/json
#

:localUrl = http://wanderer.armlfs.org.local
:api = :localUrl/api

#
GET :api/posts?posts?sortby=id&order=desc&per_page=10&page=1
:header

#
GET :api/posts/1
:header

#
POST :api/posts
:header

{
  "name": "FlippedOut",
  "body": "\u966a\u4f60\u5230\u4e16\u754c\u6d41\u6d6a"
}
